import { Product } from "../types";

export const initialProducts: Product[] = [
  {
    id: "coffee",
    name: "Cappuccino + brownie",
    shop: "cayenna",
    price: 45,
    stock: 20,
    category: "Gastronomía",
    image: "/assets/cayenna.jpeg",
  },
  {
    id: "shoes",
    name: "Zapatillas urbanas PUMA",
    shop: "puma",
    price: 590,
    stock: 8,
    category: "Moda",
    image: "/assets/puma.JPG",
  },
  {
    id: "flowers",
    name: "Ramo de flores de temporada",
    shop: "flowers",
    price: 150,
    stock: 12,
    category: "Regalos",
    image: "/assets/floristeria-flor-de-amor.webp",
  },
  {
    id: "headphones",
    name: "Audífonos Bluetooth",
    shop: "apple",
    price: 250,
    stock: 15,
    category: "Tecnología",
    image: "/assets/apple-land.webp",
  },
  {
    id: "roll",
    name: "Classic cinnamon roll",
    shop: "cinnabon",
    price: 30,
    stock: 24,
    category: "Gastronomía",
    image: "/assets/cinnabon.JPG",
  },
  {
    id: "bag",
    name: "Mochila para todos los días",
    shop: "totto",
    price: 290,
    stock: 6,
    category: "Moda",
    image: "/assets/totto.webp",
  },
  {
    id: "burger",
    name: "Combo burger + papas",
    shop: "burger",
    price: 55,
    stock: 18,
    category: "Gastronomía",
    image: "/assets/bypass-burger.webp",
  },
  {
    id: "game",
    name: "Control inalámbrico",
    shop: "games",
    price: 320,
    stock: 4,
    category: "Entretenimiento",
    image: "/assets/game-shop.webp",
  },
];

export const orderStates = [
  "Pedido recibido",
  "Pedido confirmado",
  "Preparando pedido",
  "Listo para recoger",
  "Cliente llegó al Paseo",
  "Pedido entregado",
];
